<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllSortedBy($value = 'lastname', $direction = 'ASC')
    {
        return $this->createQueryBuilder('c')
            ->orderBy('c.' . $value, $direction)
            ->getQuery()
            ->getResult();
    }
}
